[package]
name = "jed"
version = "0.1.0"
authors = ["Roger Curley <rocurley@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.11"
termion = "1.5"
serde_json = "1.0.57"
ego-tree = "0.6.1"
[dependencies.jq-rs]
version = "0.4.1"
features = ["bundled"]
